name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Install RoboRIO Toolchain
      run: ./gradlew --no-daemon installRoboRioToolchain

    - name: Build Robot Code
      run: ./gradlew --no-daemon build
      
    - name: Run Google Tests (Debug)
      run: ./gradlew --no-daemon testExternalNativeDebug

    # GoogleTest outputs may not be present yet; skip publishing if none
    - name: Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results (GoogleTest)
        path: 'build/test-results/testExternalNativeDebug/*.xml'
        reporter: java-junit
        fail-on-empty: false
