name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup WPILib
      run: |
        wget https://github.com/wpilibsuite/allwpilib/releases/download/v2025.3.2/WPILib_Linux-2025.3.2.tar.gz
        tar -xzf WPILib_Linux-2025.3.2.tar.gz
        sudo ./WPILib_Linux-2025.3.2/WPILibInstaller

    - name: Build Robot Code
      run: ./gradlew build
      
    - name: Run Tests
      run: ./gradlew test

    - name: Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: 'build/test-results/test/*.xml'
        reporter: java-junit
